sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t efamanas/hungry-discord-app -f Dockerfile.dev .

script:
  - docker run -e CI=true efamanas/hungry-discord-app npm run test

after_success:
  - docker build -t efamanas/hungry-discord-app .

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'discord'
  env: 'Discord-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-334805761658'
  bucket_path: 'discord'
  on:
    all_branches: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# TODO: Nginx conf, docker compose conf, ship token
