sudo: required
language: generic

services:
  - docker

env:
  - TOKEN=$DISCORD_TOKEN

before_install:
  - docker build -t efamanas/hungry-discord-app -f Dockerfile.dev .

script:
  - docker run -e CI=true efamanas/hungry-discord-app npm run test

after_success:
  - docker build --build-arg TOKEN=$DISCORD_TOKEN -t efamanas/hungry-discord-app .

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "discord"
  env: "Discord-env"
  bucket_name: "discord-env.eba-qfqetahz.eu-west-2.elasticbeanstalk.com"
  bucket_path: "complex"
  on:
    all_branches: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# TODO: Nginx conf, docker compose conf, ship token
